# -*- coding: utf-8 -*-
"""Лекция 5 гугл колаб.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12-2hsHwnSywj926QgahWynaydA0UzXZ0
"""

import pandas as pd

df = pd.read_csv("sample_data/california_housing_train.csv")

df.head(10)

df.tail(2)

df.shape

df.isnull().sum

df.dtypes

df.columns

df[['housing_median_age','total_rooms']]

df[df['housing_median_age'] < 20]

"""& - выполнение одновременно **всех** условий (и, and)

| - выполнение **хотя бы одного** условия. (или, or)
"""

df[(df['housing_median_age'] < 20) & (df["housing_median_age"] > 10)][["total_rooms","housing_median_age"]]

print(df["population"].max())
print(df["population"].mean())
print(df["population"].min())
print(df["population"].sum())
print(df[["population","total_rooms"]].median())

df.describe()

df.isnull().sum()

"""count -Общее кол-во не пустых строк

mean -среднее значение в столбце

std -стандартное отклонение от среднего значения

min -минимальное значение

max -максимальное значение

Числа 25%, 50%, 75% -перцентили
"""

